### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by ThomasCampredon** [AOx0/Digital-Logic-Sim-CE#10]
Hello sir, 
could you make a downloadable linux version please ?

**Comment by AOx0** [comment]
Sure, I will publish it anytime today or tomorrow.

**Comment by AOx0** [comment]
Omg, how has a week already passed? I will do it this week. Sorry. :/

**Comment by MarcosFarias21** [comment]
Please linux version! Please!

**Comment by AOx0** [comment]
The newest release fixes #11 and provides a Linux build. Please let me know if everything works fine.

**Comment by MarcosFarias21** [comment]
Thank you so much! I wish I could contribute but I'm just a frontend student who only knows some javascript, a bit of python and lua. anyway this app is helping to understand how computers work and get familiar with the binary system.

**Comment by MarcosFarias21** [comment]
the linux version is working perfecly until now, if I find some bug i'll let you know.

**Comment by AOx0** [comment]
Great! Thanks for the feedback. I will now close this issue.
