### ISSUE TITLE
Can't save a new ship after updating another one

### ISSUE THREAD

**Issue by ThomasCampredon** [AOx0/Digital-Logic-Sim-CE#11]
All is in the title, after an update, the save button does not reappear and I'm stuck with the update button

**Comment by AOx0** [comment]
Yep, noticed this yesterday. I'm going to work on a fix after my exams finish (end of the week)

**Comment by AOx0** [comment]
Fixed this issue with 41a9408deb512ee73f77cdc98f501c393d83d14a
