### ISSUE TITLE
Chip import crash with old saves

### ISSUE THREAD

**Issue by AOx0** [AOx0/Digital-Logic-Sim-CE#17]
Trying to import a chip from a very old save straight up crashes the game.
Does not happen on newer game saves. (Created with v0.38 I suspect)

**Comment by VitoBarra** [comment]
save file of witch version? i can try to fix the problem

**Comment by AOx0** [comment]
Well I'm unable to reproduce the problem. So maybe it's a false positive.

**Comment by AOx0** [comment]
Yup, probably I was too sleepy and did something wrong.
